### **自定义层**

**构造一个没有任何参数的自定义层**

In [4]:
import torch
import torch.nn.functional as F
from torch import nn

class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()
    
    def forward(self, X):
        return X - X.mean()

layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

**将层作为组件合并到构建更复杂的模型中**

In [5]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())

Y = net(torch.rand(4, 8))
Y.mean()    # 由于浮点数的精度限制，返回的结果不是0

tensor(5.5879e-09, grad_fn=<MeanBackward0>)

**带参数的图层**

In [6]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))
    
    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

dense = MyLinear(5, 3)
dense.weight

Parameter containing:
tensor([[-1.1459, -0.3781,  1.0254],
        [ 1.3429,  0.8436, -1.6935],
        [ 0.1671, -0.5012,  0.1153],
        [ 0.8406, -0.2755, -0.1781],
        [-1.2567,  0.9378,  0.6822]], requires_grad=True)

**使用自定义层直接执行正向传播计算**

In [7]:
dense(torch.rand(2, 5))

tensor([[0.6984, 0.6615, 0.0000],
        [0.0586, 0.9938, 0.0000]])

**使用自定义层构建模型**

In [8]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[0.],
        [0.]])