- 矩阵 ✖ 向量 = 向量  **事实上相当于对于向量在空间上做了一个扭曲**

### 置换矩阵
置换矩阵是一种特殊类型的方阵，**其作用是对向量或坐标进行重新排列**。在线性代数和数学中，置换矩阵也称为排列矩阵或置换算符。

一个 n × n 的置换矩阵可以将 n 维空间中的向量重新排列，其定义如下：

设 P 是一个 n × n 的方阵，如果满足以下两个条件，则称 P 为一个置换矩阵：

1. 矩阵 P 中的每个元素只能取值为 0 或 1。
2. 每一行和每一列都有且仅有一个元素为 1，其余元素都为 0。

**换句话说，置换矩阵是一种特殊的二进制矩阵，每一行和每一列都只有一个元素为 1，其余为 0，且每一行和每一列的 1 都不在其他行或列中重复。**

**在矩阵乘法中，如果一个向量用一个置换矩阵左乘，那么这个置换矩阵会改变向量的顺序。它类似于在向量空间中对向量进行重新排列，而不改变向量之间的线性关系**。

置换矩阵在很多领域中都有应用，尤其在图论、密码学、组合数学以及计算机科学中经常被使用。在计算机图形学中，**置换矩阵可以用于实现图像的平移、旋转和缩放等操作**。

---------------------------

### 特征向量和特征值
特征向量和特征值是线性代数中矩阵的重要性质，它们在矩阵和向量空间的理解和应用中起着关键的作用。

1. 特征向量（Eigenvector）：
对于一个 n × n 的方阵 A，非零向量 v 被称为 A 的特征向量，如果满足以下条件：
\[Av = $\lambda$ v\]
其中，A 是矩阵，v 是一个非零向量，λ 是一个标量（实数或复数）。**特征向量表示在矩阵变换下方向不变，只发生伸缩的向量**。

**特征向量不是唯一的**，任意一个与 v 成比例的向量（即 kv，其中 k 是非零标量）也是 A 的特征向量，因为它们在伸缩下具有相同的性质。

2. 特征值（Eigenvalue）：
对于一个 n × n 的方阵 A，**特征值是一个标量（实数或复数）**，记为 λ。特征值满足以下条件：
\[Av = $\lambda$ v\]
其中，A 是矩阵，v 是 A 的特征向量，λ 是对应于 v 的特征值。

**每个特征向量都有一个对应的特征值。特征值表示特征向量在矩阵变换下的缩放因子**。如果 v 是 A 的特征向量，并且 λ 是对应的特征值，则在进行线性变换 A 时，v 的方向保持不变，但长度会变为 λ 倍。

3. 求解特征向量和特征值：
要求解一个矩阵 A 的特征向量和特征值，需要解决以下方程：
\[(A - $\lambda$ I) v = 0\]
其中，I 是 n × n 的单位矩阵，0 是 n 维的零向量。

上述方程是一个齐次线性方程组，**非零解 v 存在的条件**是矩阵 (A - λI) 的行列式为零，即 \(|A - $\lambda$ I| = 0\)。解出的 λ 即为特征值，而对应每个特征值的非零解 v 即为特征向量。


> 对称矩阵总是可以找到特征向量

--------------------------------------------------

In [1]:
# 标量由只有一个元素的张量表示

import torch

x = torch.tensor([3.0])
y = torch.tensor([2.0])

x + y, x * y, x / y, x**y


(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

In [2]:
# 向量可以视为标量值组成的列表
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [3]:
# 通过张量的索引来访问任一元素
x[3]

tensor(3)

In [4]:
# 访问张量的长度
len(x)

4

In [5]:
# 只有一个轴的张量，形状只有一个元素
x.shape

torch.Size([4])

In [6]:
# 通过指定两个分量m和n来创建一个m×n的矩阵
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [7]:
# 矩阵的转置
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [8]:
# 对称矩阵（symmertric matrix）：$A = A^T$
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [9]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [10]:
# 就像向量是标量的推广，矩阵是向量的推广一样，我们可以构建具有更多轴的数据结构
X = torch.arange(24).reshape(2, 3, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [11]:
# 给定具有相同形状的任何两个张量，任何按元素二元运算的结果都将是相同形状的张量
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()  # 通过分配新内存，将A的一个副本分配给B
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [12]:
# 两个矩阵的按元素乘法称为哈达玛积（Hadamard product）（数学符号⊙）。
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [13]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

In [14]:
# 计算其元素的和
x = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [15]:
# 表示任意形状张量的元素和
A = torch.arange(20 * 2, dtype=torch.float32).reshape(2, 5, 4)
A.shape, A.sum()

(torch.Size([2, 5, 4]), tensor(780.))

In [17]:
# 指定求和汇总张量的轴
A_sum_axis0 = A.sum(axis=0)  # type: ignore
A_sum_axis0, A_sum_axis0.shape

(tensor([[20., 22., 24., 26.],
         [28., 30., 32., 34.],
         [36., 38., 40., 42.],
         [44., 46., 48., 50.],
         [52., 54., 56., 58.]]),
 torch.Size([5, 4]))

In [20]:
A_sum_axis1 = A.sum(axis=1)  # type: ignore
A_sum_axis1, A_sum_axis1.shape

(tensor([[ 40.,  45.,  50.,  55.],
         [140., 145., 150., 155.]]),
 torch.Size([2, 4]))

In [21]:
A.sum(axis=[0, 1])  # type: ignore


tensor([180., 190., 200., 210.])

In [22]:
# 一个与求和相关的量是平均值（mean或average）
A.mean(), A.sum() / A.numel()

(tensor(19.5000), tensor(19.5000))

In [36]:
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([[10., 11., 12., 13.],
         [14., 15., 16., 17.],
         [18., 19., 20., 21.],
         [22., 23., 24., 25.],
         [26., 27., 28., 29.]]),
 tensor([[10., 11., 12., 13.],
         [14., 15., 16., 17.],
         [18., 19., 20., 21.],
         [22., 23., 24., 25.],
         [26., 27., 28., 29.]]))

> 计算总和或均值时保持轴数不变

In [25]:
sum_A = A.sum(axis=0, keepdims=True)
sum_A, sum_A.shape

(tensor([[[20., 22., 24., 26.],
          [28., 30., 32., 34.],
          [36., 38., 40., 42.],
          [44., 46., 48., 50.],
          [52., 54., 56., 58.]]]),
 torch.Size([1, 5, 4]))

In [27]:
# 通过广播将A除以sum_A
A / sum_A

tensor([[[0.0000, 0.0455, 0.0833, 0.1154],
         [0.1429, 0.1667, 0.1875, 0.2059],
         [0.2222, 0.2368, 0.2500, 0.2619],
         [0.2727, 0.2826, 0.2917, 0.3000],
         [0.3077, 0.3148, 0.3214, 0.3276]],

        [[1.0000, 0.9545, 0.9167, 0.8846],
         [0.8571, 0.8333, 0.8125, 0.7941],
         [0.7778, 0.7632, 0.7500, 0.7381],
         [0.7273, 0.7174, 0.7083, 0.7000],
         [0.6923, 0.6852, 0.6786, 0.6724]]])

> 某个轴计算A元素的累积总和

In [34]:
A.cumsum(axis=0)

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]],

        [[20., 22., 24., 26.],
         [28., 30., 32., 34.],
         [36., 38., 40., 42.],
         [44., 46., 48., 50.],
         [52., 54., 56., 58.]]])

In [36]:
# 点积是相同位置的按元素乘积的和
y = torch.ones(4, dtype=torch.float32)
x, y ,torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [37]:
# 我们可以通过执行按元素乘法，然后进行求和来表示两个向量的点积
torch.sum(x * y)

tensor(6.)

> 矩阵向量积Ax是一个长度为m的列向量，其$i^{th}$元素是点积$a_i^T x$

In [39]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)

In [41]:
A.shape, x.shape, torch.mv(A, x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

In [42]:
# 我们可以将矩阵-矩阵乘法AB看作是简单地执行m次矩阵-向量积，并将结果拼接在一起，形成一个n×m矩阵。
B = torch.ones(4, 3)
torch.mm(A, B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

$L_2$范数是向量元素平方和的平方根：
$$\|\mathbf{x}\|_2 = \sqrt{\sum_{i=1}^n x_i^2},$$

In [44]:
u = torch.tensor([3.0, -4.0])
torch.norm(u) # 求范数

tensor(5.)

$L_1$范数，它表示为向量元素的绝对值之和：
$$\|\mathbf{x}\|_1 = \sum_{i=1}^n \left|x_i \right|.$$

In [45]:
torch.abs(u).sum()

tensor(7.)

矩阵的弗罗贝尼乌斯范数（Frobenius norm）是矩阵元素的平方和的平方根：

$$\|\mathbf{X}\|_F = \sqrt{\sum_{i=1}^m \sum_{j=1}^n x_{ij}^2}.$$

In [47]:
torch.norm(torch.ones((4, 9)))

tensor(6.)

In [48]:
# torch如果想要区分行向量和列向量，需要使用矩阵来表示
a = torch.arange(5).reshape(1, 5)   # 行向量
b = torch.arange(5).reshape(5, 1)   # 列向量
a, b

(tensor([[0, 1, 2, 3, 4]]),
 tensor([[0],
         [1],
         [2],
         [3],
         [4]]))